# Generated by Django 5.0.1 on 2024-03-18 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='istagram',
            new_name='instagram',
        ),
    ]
